name: Random Number Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          mkdir -p history20/$(date +"%y/%m/%d")
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "FILE_PREFIX=m" >> $GITHUB_ENV
          else
            echo "FILE_PREFIX=" >> $GITHUB_ENV
          fi
          echo "RELATIVE_PATH=history20/$(date +"%y/%m/%d/")${FILE_PREFIX}$(date +"%H.txt")" >> $GITHUB_ENV
      
      - name: Generate random number
        run: |
          xxd -c 64 -l 2048 -p /dev/random > history20/$(date +"%y/%m/%d/")${FILE_PREFIX}$(date +"%H.txt")
          if [ "${{ github.event_name }}" = "schedule" ]; then
            ln -sf "$RELATIVE_PATH" current
          fi
      
      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [ "${{ github.event_name }}" = "schedule" ]; then
            git add history20 current
          else
            git add history20
          fi
          git commit -S -m "Add random number for $(date +"%Y-%m-%d %H:00") (${FILE_PREFIX:+manual trigger}${FILE_PREFIX:-scheduled})"
          git push
